# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Junteng Liu
email: jliugi@connect.ust.hk
description: >- # this means to ignore newlines until "baseurl:"
  First-year PhD candidate at HKUST NLP Group. Research focuses on natural language processing and machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: junteng88716710
github_username: Vicent0205
repository: andygyx/LJT-Homepage

# Set permalink style
permalink: /:categories/:title/

# Site Author
author:
  name: "Junteng Liu"
  avatar: # path to the sidebar avatar image, e.g. "/images/bio-photo.jpg"
  bio: "First-year PhD candidate at HKUST NLP Group, advised by Professor Junxian He. Research focuses on natural language processing and machine learning."
  location: ""
  email: jliugi@connect.ust.hk
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: /page:num/

# Collections
collections:
  publications:
    output: true
  talks:
    output: true
  portfolio:
    output: true
  teaching:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
